os:
  - linux
  - osx
language: generic
sudo: required
dist: bionic
osx_image: xcode11
addons:
  apt:
    update: true
    packages:
      - pkg-config
      - libassimp-dev
  homebrew:
    update: true
    packages:
      - pkg-config
      - assimp
#install:
  #- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift package reset
  - swift build
  - swift test