os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode11
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install assimp; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y -qq pkg-config libassimp-dev; fi
script:
  - swift package reset
  - swift build
  - swift test
env:
  - BADGE=linux
  - BADGE=osx
# hack to get some OS-specific badges 
# see: https://github.com/travis-ci/travis-ci/issues/9579
matrix:
  exclude:
    - os: linux
      env: BADGE=osx
    - os: osx
      env: BADGE=linux
