os:
  - linux
  - osx
language: generic
sudo: required
dist: bionic
osx_image: xcode11
addons:
  apt:
    update: true
    packages:
      - pkg-config
      - assimp
  homebrew:
    update: true
    packages:
      - pkg-config
      - assimp
## install:
##   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install assimp; fi
##   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --reinstall install -y pkg-config libassimp-dev; fi
##   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-cache madison assimp; fi
##   - pkg-config assimp --cflags --libs --static
##   - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift package reset
  - swift build
  - swift test