os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode11
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update --allow-unauthenticated; fi
addons:
  apt:
    update: true
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install assimp; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --reinstall install -y pkg-config libassimp-dev=4.1.0\*; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-cache madison assimp; fi
  - pkg-config assimp --cflags --libs --static
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift package reset
  - swift build
  - swift test
env:
  - BADGE=linux
  - BADGE=osx
# hack to get some OS-specific badges 
# see: https://github.com/travis-ci/travis-ci/issues/9579
matrix:
  exclude:
    - os: linux
      env: BADGE=osx
    - os: osx
      env: BADGE=linux
